export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const SET_IS_EDIT = 'SET_IS_EDIT';
export const SET_CURRENT_ACCOUNT_ID = 'SET_CURRENT_ACCOUNT_ID';
export const SET_VISIT_ACCOUNT_ID = 'SET_VISIT_ACCOUNT_ID';
// export const ADD_NEW_ACCOUNT = 'ADD_NEW_ACCOUNT';
// export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const ADD_NEW_ARTICLE = 'ADD_NEW_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const ADD_NEW_ARTICLE_REQUEST = 'ADD_NEW_ARTICLE_REQUEST';
export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST';

export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
